version: '3.9'
services:
  glances:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "61208:61208"
    environment:
      GLANCES_OPT: "--server --disable-webui --disable-history"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - "./glances.conf:/glances/conf/glances.conf"
    pid: "host"
    privileged: true
    network_mode: "host"