services:
  vaultwarden:
    image: "${VAULTWARDEN_IMAGE:-vaultwarden/server:latest}"
    container_name: vaultwarden
    ports:
    - 8089:80
    - 3012:3012
    volumes:
    - "./vw-data:/data"
    restart: always
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      DOMAIN: "${DOMAIN:-https://pass.example.com}"
      SMTP_HOST: "${SMTP_HOST:-smtp.example.com}"
      SMTP_FROM: "${SMTP_FROM:-homelab@example.com}"
      SMTP_PORT: "${SMTP_PORT:-587}"
      SMTP_SECURITY: "${SMTP_SECURITY:-starttls}"
      SMTP_TIMEOUT: "${SMTP_TIMEOUT:-15}"
      SMTP_USERNAME: "${SMTP_USERNAME:-homelab@example.com}"
      SMTP_PASSWORD: "${SMTP_PASSWORD:-}"
