version: "3"

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - './vw-data:/data'
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN=https://mypassstore.com
      - ADMIN_TOKEN=''
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_FROM=visesh@live.com
      - SMTP_PORT=465
      - SMTP_SECURITY=force_tls
      - SMTP_TIMEOUT=15
      - SMTP_USERNAME=apikey
      - SMTP_PASSWORD=''
    ports:
      - '8080:80'
      - '3012:3012'
    restart: always
