services:
  planka:
    image: "${PLANKA_IMAGE:-ghcr.io/plankanban/planka:2.2.1@sha256:125f45330853210c678fed1132bedc0912b4a11a27779b79802fbca108e069e2}"
    ports:
    - 3001:1337
    volumes:
    - data:/app/data
    depends_on:
    - postgres
    restart: unless-stopped
    environment:
      BASE_URL: "${BASE_URL:-https://boards.example.com}"
      TRUST_PROXY: 'true'
      DATABASE_URL: "${DATABASE_URL:-postgresql://postgres@postgres/planka}"
      SECRET_KEY: "${SECRET_KEY:?Set SECRET_KEY}"
  postgres:
    image: "${POSTGRES_IMAGE:-postgres:14-alpine}"
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: planka
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  data:
  db-data:
