services:
  broker:
    image: "${BROKER_IMAGE:-docker.io/library/redis:7}"
    volumes:
    - redisdata:/data
    restart: unless-stopped
  webserver:
    image: "${WEBSERVER_IMAGE:-ghcr.io/paperless-ngx/paperless-ngx:latest}"
    ports:
    - 8000:8000
    volumes:
    - data:/usr/src/paperless/data
    - media:/usr/src/paperless/media
    - "./export:/usr/src/paperless/export"
    - "./consume:/usr/src/paperless/consume"
    depends_on:
    - broker
    - gotenberg
    - tika
    restart: unless-stopped
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    env_file: docker-compose.env
  gotenberg:
    image: "${GOTENBERG_IMAGE:-docker.io/gotenberg/gotenberg:7.8}"
    restart: unless-stopped
    command:
    - gotenberg
    - "--chromium-disable-javascript=true"
    - "--chromium-allow-list=file:///tmp/.*"
  tika:
    image: "${TIKA_IMAGE:-ghcr.io/paperless-ngx/tika:latest}"
    restart: unless-stopped
volumes:
  data:
  media:
  redisdata:
