version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - './filebrowser.db:/database/filebrowser.db'
      - './settings.json:/config/settings.json'
      - '/mnt:/srv'
    ports:
      - 8080:80
    restart: unless-stopped
