[
  {"name": "docker.io/crazymax/diun:latest", "notify_on": ["update"]},
  {"name": "docker.io/amir20/dozzle:latest", "notify_on": ["update"]},
  {
    "name": "ghcr.io/wg-easy/wg-easy:15",
    "watch_repo": true,
    "notify_on": ["new"],
    "include_tags": ["^(1[6-9]|[2-9][0-9]+)$"]
  },
  {
    "name": "docker.io/library/postgres:15",
    "watch_repo": true,
    "notify_on": ["new"],
    "include_tags": ["^(1[6-9]|[2-9][0-9]+)$"]
  }
]
