services:
  archivebox:
    image: "${DOCKER_IMAGE:-archivebox/archivebox:dev}"
    ports:
    - 8002:8000
    volumes:
    - "./data:/data"
    restart: always
    environment:
      MEDIA_MAX_SIZE: 1500m
      TIMEOUT: '120'
      CHECK_SSL_VALIDITY: 'True'
      PUBLIC_INDEX: 'False'
      PUBLIC_SNAPSHOTS: 'False'
      PUBLIC_ADD_VIEW: 'False'
    command: server --quick-init 0.0.0.0:8000
    dns:
    - "${DNS_SERVER:?Set DNS_SERVER}"
  pywb:
    image: "${PYWB_IMAGE:-webrecorder/pywb:latest}"
    ports:
    - 8082:8080
    volumes:
    - "./data:/archivebox"
    - "./data/wayback:/webarchive"
    restart: always
    entrypoint: "/bin/sh -c '(wb-manager init default || test $$? -eq 2) && wb-manager
      add default /archivebox/archive/*/warc/*.warc.gz; wayback;'"
    environment:
      INIT_COLLECTION: "${INIT_COLLECTION:-archivebox}"
