# Usage:
#     docker-compose run archivebox init --setup
#     docker-compose up
#     echo "https://example.com" | docker-compose run archivebox archivebox add
#     docker-compose run archivebox add --depth=1 https://example.com/some/feed.rss
#     docker-compose run archivebox config --set PUBLIC_INDEX=True
#     docker-compose run archivebox help
# Documentation:
#     https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#docker-compose

version: '2.4'

services:
    archivebox:
        image: ${DOCKER_IMAGE:-archivebox/archivebox:master}
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - ./data:/data
        dns:                                           # uncomment this and pihole container below for ad-blocking during archiving
            - 192.168.68.77
        environment:
            - ALLOWED_HOSTS=*                   # restrict this to only accept incoming traffic via specific domain name
            - MEDIA_MAX_SIZE=750m             # increase this filesize limit to allow archiving larger audio/video files
            # - TIMEOUT=60                      # increase this number to 120+ seconds if you see many slow downloads timing out
            - CHECK_SSL_VALIDITY=True         # set to False to disable strict SSL checking (allows saving URLs w/ broken certs)
            - SAVE_ARCHIVE_DOT_ORG=False       # set to False to disable submitting all URLs to Archive.org when archiving
            - PUBLIC_INDEX=False               # set to False to prevent anonymous users from viewing snapshot list
            - PUBLIC_SNAPSHOTS=False           # set to False to prevent anonymous users from viewing snapshot content
            - PUBLIC_ADD_VIEW=False           # set to True to allow anonymous users to submit new URLs to archive
            # - PUID=1000                       # set to your host user's UID & GID if you encounter permissions issues
            # - PGID=1000
            # ...
            # add further configuration options from archivebox/config.py as needed (to apply them only to this container)
            # or set using `docker compose run archivebox config --set SOME_KEY=someval` (to persist config across all containers)
        restart: always

    # Example: Run PYWB in parallel and auto-import WARCs from ArchiveBox
    pywb:
        image: webrecorder/pywb:latest
        entrypoint: /bin/sh -c '(wb-manager init default || test $$? -eq 2) && wb-manager add default /archivebox/archive/*/warc/*.warc.gz; wayback;'
        environment:
            - INIT_COLLECTION=archivebox
        ports:
            - 8080:8080
        volumes:
            - ./data:/archivebox
            - ./data/wayback:/webarchive
        restart: always
