services:
  dozzle:
    image: "${DOZZLE_IMAGE:-amir20/dozzle:latest}"
    ports:
    - 8080:8080
    volumes:
    - "./data:/data"
    - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    environment:
      CONTAINERS: "${CONTAINERS:-}"
      DOZZLE_REMOTE_HOST: "${DOZZLE_REMOTE_HOST:-}"
      DOZZLE_NO_ANALYTICS: 'true'
      DOZZLE_AUTH_PROVIDER: simple
