services:
  firezone:
    image: "${FIREZONE_IMAGE:-firezone/firezone:latest}"
    ports:
    - 51820:51820/udp
    - 13000:13000
    volumes:
    - "${FZ_INSTALL_DIR:-.}/firezone:/var/firezone"
    networks:
      firezone-network:
        ipv4_address: 172.25.0.100
        ipv6_address: "${FZ_IPV6_ADDRESS:-fd25:3990:3990::99}"
    depends_on:
    - postgres
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.all.forwarding=1
    env_file:
    - "${FZ_INSTALL_DIR:-.}/.env"
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      update_config:
        order: start-first
  postgres:
    image: "${POSTGRES_IMAGE:-postgres:15}"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    networks:
    - firezone-network
    environment:
      POSTGRES_DB: "${DATABASE_NAME:-firezone}"
      POSTGRES_USER: "${DATABASE_USER:-postgres}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:?Set DATABASE_PASSWORD}"
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s
      update_config:
        order: stop-first
volumes:
  postgres-data:
networks:
  firezone-network:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/16
      - subnet: "${FZ_IPV6_SUBNET:-fd25:3990:3990::/64}"
        gateway: "${FZ_IPV6_GATEWAY:-fd25:3990:3990::1}"
