version: "3.7"

services:
  fail2ban:
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=UTC
      - F2B_DB_PURGE_AGE=14d
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
    image: crazymax/fail2ban:latest
    network_mode: host
    restart: always
    volumes:
      - "./data:/data"
      - "/opt/nginx/data/logs:/var/log/npm"
      - "/var/log/auth.log:/var/log/auth.log:ro"
