services:
  fail2ban:
    image: "${FAIL2BAN_IMAGE:-crazymax/fail2ban:latest}"
    container_name: fail2ban
    volumes:
    - "./data:/data"
    - "${NPM_LOG_DIR:-/opt/nginx/data/logs}:/var/log/npm:ro"
    - "/var/log/auth.log:/var/log/auth.log:ro"
    network_mode: host
    restart: always
    cap_add:
    - NET_ADMIN
    - NET_RAW
    environment:
      TZ: UTC
      F2B_DB_PURGE_AGE: 14d
      F2B_LOG_TARGET: STDOUT
      F2B_LOG_LEVEL: INFO
