# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
    customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

ffmpeg:

wake_on_lan:

sun:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_network

binary_sensor:
  - platform: ping
    host: !secret presence_device_one
    name: presence_device_one
    count: 8
    scan_interval: 15
  - platform: ping
    host: !secret presence_device_two
    name: presence_device_two
    count: 8
    scan_interval: 15
  - platform: ping
    host: !secret proxy_host
    name: rpiproxy
    count: 8
    scan_interval: 15
