version: "3"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
    volumes:
      - './config:/config'
      - './tv:/tv'
      - './movies:/movies'
#      - '/mnt/nfsshare:/share'
      - '/mnt/media:/mnt/media'
    restart: unless-stopped
