services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
    - "${HOMEBRIDGE_DATA_DIR:?Set HOMEBRIDGE_DATA_DIR}:/homebridge"
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
