services:
  uptime-kuma:
    image: "${UPTIME_KUMA_IMAGE:-louislam/uptime-kuma:latest}"
    container_name: uptime-kuma
    ports:
    - 3001:3001
    volumes:
    - "./uptime-kuma-data:/app/data"
    restart: always
