services:
  pihole:
    image: "${PIHOLE_IMAGE:-pihole/pihole:latest}"
    container_name: pihole
    volumes:
    - "./etc-pihole:/etc/pihole"
    - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    network_mode: host
    restart: always
    cap_add:
    - NET_ADMIN
    environment:
      TZ: America/New_York
      WEBPASSWORD: "${WEBPASSWORD:?Set WEBPASSWORD}"
      QUERY_LOGGING: "${QUERY_LOGGING:-true}"
      DHCP_IPv6: "${DHCP_IPv6:-false}"
